<?php
if (($freightco_slider_sc = freightco_get_theme_option('front_page_title_shortcode')) != '' && strpos($freightco_slider_sc, '[')!==false && strpos($freightco_slider_sc, ']')!==false) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider"><?php
		// Add anchor
		$freightco_anchor_icon = freightco_get_theme_option('front_page_title_anchor_icon');	
		$freightco_anchor_text = freightco_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($freightco_anchor_icon) || !empty($freightco_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($freightco_anchor_icon) ? ' icon="'.esc_attr($freightco_anchor_icon).'"' : '')
											. (!empty($freightco_anchor_text) ? ' title="'.esc_attr($freightco_anchor_text).'"' : '')
											. ']');
		}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode($freightco_slider_sc);
	?></div><?php

} else {

	?><div class="front_page_section front_page_section_title<?php
				$freightco_scheme = freightco_get_theme_option('front_page_title_scheme');
				if (!freightco_is_inherit($freightco_scheme)) echo ' scheme_'.esc_attr($freightco_scheme);
				echo ' front_page_section_paddings_'.esc_attr(freightco_get_theme_option('front_page_title_paddings'));
			?>"<?php
			$freightco_css = '';
			$freightco_bg_image = freightco_get_theme_option('front_page_title_bg_image');
			if (!empty($freightco_bg_image)) 
				$freightco_css .= 'background-image: url('.esc_url(freightco_get_attachment_url($freightco_bg_image)).');';
			if (!empty($freightco_css))
				echo ' style="' . esc_attr($freightco_css) . '"';
	?>><?php
		// Add anchor
		$freightco_anchor_icon = freightco_get_theme_option('front_page_title_anchor_icon');	
		$freightco_anchor_text = freightco_get_theme_option('front_page_title_anchor_text');	
		if ((!empty($freightco_anchor_icon) || !empty($freightco_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($freightco_anchor_icon) ? ' icon="'.esc_attr($freightco_anchor_icon).'"' : '')
											. (!empty($freightco_anchor_text) ? ' title="'.esc_attr($freightco_anchor_text).'"' : '')
											. ']');
		}
		?>
		<div class="front_page_section_inner front_page_section_title_inner<?php
			if (freightco_get_theme_option('front_page_title_fullheight'))
				echo ' freightco-full-height sc_layouts_flex sc_layouts_columns_middle';
			?>"<?php
				$freightco_css = '';
				$freightco_bg_mask = freightco_get_theme_option('front_page_title_bg_mask');
				$freightco_bg_color = freightco_get_theme_option('front_page_title_bg_color');
				if (!empty($freightco_bg_color) && $freightco_bg_mask > 0)
					$freightco_css .= 'background-color: '.esc_attr($freightco_bg_mask==1
																		? $freightco_bg_color
																		: freightco_hex2rgba($freightco_bg_color, $freightco_bg_mask)
																	).';';
				if (!empty($freightco_css))
					echo ' style="' . esc_attr($freightco_css) . '"';
		?>>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$freightco_caption = freightco_get_theme_option('front_page_title_caption');
				if (!empty($freightco_caption) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo !empty($freightco_caption) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post($freightco_caption); ?></h1><?php
				}
			
				// Description (text)
				$freightco_description = freightco_get_theme_option('front_page_title_description');
				if (!empty($freightco_description) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo !empty($freightco_description) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post(wpautop($freightco_description)); ?></div><?php
				}
				
				// Buttons
				if (freightco_get_theme_option('front_page_title_button1_link')!='' || freightco_get_theme_option('front_page_title_button2_link')!='') {
					?><div class="front_page_section_buttons front_page_section_title_buttons"><?php
						freightco_show_layout(freightco_customizer_partial_refresh_front_page_title_button1_link());
						freightco_show_layout(freightco_customizer_partial_refresh_front_page_title_button2_link());
					?></div><?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}